{
  "hash": "bc997fc6eedd2d11238070b9a5757256",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Spatial Analysis and Visualization\"\nsubtitle: \"Healthcare Access and Equity in Pennsylvania\"\nauthor: \"Qianmu Zheng\"\ndate: today\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n## Assignment Overview\n\n**Learning Objectives:**\n- Apply spatial operations to answer policy-relevant research questions\n- Integrate census demographic data with spatial analysis\n- Create publication-quality visualizations and maps\n- Work with spatial data from multiple sources\n- Communicate findings effectively for policy audiences\n\n---\n\n## Part 1: Healthcare Access for Vulnerable Populations\n\n### Research Question\n\n**Which Pennsylvania counties have the highest proportion of vulnerable populations (elderly + low-income) living far from hospitals?**\n\n\n#### Step 1: Data Collection (5 points)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages\nlibrary(sf)\nlibrary(tidyverse)\nlibrary(tigris)\nlibrary(tidycensus)\nlibrary(scales)\nlibrary(patchwork)\nlibrary(here)\n# Load spatial data\ndata_path <- \"D:/Desktop/musa/5080_policy/5080/MUSA-5080-Fall-2025/lectures/week-04/data\"\ncensus_api_key(\"940dffa67b928a0518accaf8839aa7b4762b11ab\")\n\npa_counties <- st_read(file.path(data_path, \"Pennsylvania_County_Boundaries.shp\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Pennsylvania_County_Boundaries' from data source \n  `D:\\Desktop\\musa\\5080_policy\\5080\\MUSA-5080-Fall-2025\\lectures\\week-04\\data\\Pennsylvania_County_Boundaries.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 67 features and 19 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -8963377 ymin: 4825316 xmax: -8314404 ymax: 5201413\nProjected CRS: WGS 84 / Pseudo-Mercator\n```\n\n\n:::\n\n```{.r .cell-code}\nhospitals <- st_read(file.path(data_path, \"hospitals.geojson\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `hospitals' from data source \n  `D:\\Desktop\\musa\\5080_policy\\5080\\MUSA-5080-Fall-2025\\lectures\\week-04\\data\\hospitals.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 223 features and 11 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -80.49621 ymin: 39.75163 xmax: -74.86704 ymax: 42.13403\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\ncensus_tracts <- tracts(state = \"PA\", cb = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |======================================================================| 100%\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check that all data loaded correctly\nhospitals <- st_transform(hospitals, st_crs(pa_counties))\ncensus_tracts <- st_transform(census_tracts, st_crs(pa_counties))\n\nhead(pa_counties)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 6 features and 19 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -8905670 ymin: 4862594 xmax: -8317930 ymax: 5161279\nProjected CRS: WGS 84 / Pseudo-Mercator\n  OBJECTID MSLINK COUNTY_NAM COUNTY_NUM FIPS_COUNT COUNTY_ARE COUNTY_PER\n1      336     46 MONTGOMERY         46        091       <NA>       <NA>\n2      337      8   BRADFORD         08        015       <NA>       <NA>\n3      338      9      BUCKS         09        017       <NA>       <NA>\n4      339     58      TIOGA         58        117       <NA>       <NA>\n5      340     59      UNION         59        119       <NA>       <NA>\n6      341     60    VENANGO         60        121       <NA>       <NA>\n  NUMERIC_LA COUNTY_N_1 AREA_SQ_MI SOUND SPREAD_SHE IMAGE_NAME NOTE_FILE VIDEO\n1          5         46   487.4271  <NA>       <NA>   poll.bmp      <NA>  <NA>\n2          2          8  1161.3379  <NA>       <NA>   poll.bmp      <NA>  <NA>\n3          5          9   622.0836  <NA>       <NA>   poll.bmp      <NA>  <NA>\n4          2         58  1137.2480  <NA>       <NA>   poll.bmp      <NA>  <NA>\n5          2         59   319.1893  <NA>       <NA>   poll.bmp      <NA>  <NA>\n6          3         60   683.3676  <NA>       <NA>   poll.bmp      <NA>  <NA>\n  DISTRICT_N PA_CTY_COD MAINT_CTY_ DISTRICT_O                       geometry\n1         06         46          4        6-4 MULTIPOLYGON (((-8398884 48...\n2         03         08          9        3-9 MULTIPOLYGON (((-8558633 51...\n3         06         09          1        6-1 MULTIPOLYGON (((-8367360 49...\n4         03         59          7        3-7 MULTIPOLYGON (((-8558633 51...\n5         03         60          8        3-8 MULTIPOLYGON (((-8562865 49...\n6         01         61          5        1-5 MULTIPOLYGON (((-8870781 50...\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(hospitals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 6 features and 11 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -8936626 ymin: 4838244 xmax: -8367892 ymax: 4901278\nProjected CRS: WGS 84 / Pseudo-Mercator\n                 CHIEF_EXEC              CHIEF_EX_1\n1             Peter J Adamo               President\n2          Autumn DeShields Chief Executive Officer\n3              Shawn Parekh Chief Executive Officer\n4               DIANE HRITZ Chief Executive Officer\n5            Tim Harclerode Chief Executive Officer\n6 Richard McLaughlin MD MBA Chief Executive Officer\n                      FACILITY_U LONGITUDE       COUNTY\n1   https://www.phhealthcare.org -79.91131   Washington\n2      https://www.malvernbh.com -75.17005 Philadelphia\n3 https://roxboroughmemorial.com -75.20963 Philadelphia\n4     https://www.ashospital.net -80.27907   Washington\n5      https://www.conemaugh.org -79.02513     Somerset\n6        https://towerhealth.org -75.61213   Montgomery\n                               FACILITY_N                         STREET\n1               Penn Highlands Mon Valley         1163 Country Club Road\n2               MALVERN BEHAVIORAL HEALTH 1930 South Broad Street Unit 4\n3            Roxborough Memorial Hospital              5800 Ridge Avenue\n4              ADVANCED SURGICAL HOSPITAL       100 TRICH DRIVE\\nSUITE 1\n5 DLP Conemaugh Meyersdale Medical Center             200 Hospital Drive\n6                 Pottstown Hospital, LLC          1600 East High Street\n    CITY_OR_BO LATITUDE   TELEPHONE_ ZIP_CODE                 geometry\n1  Monongahela 40.18193 724-258-1000    15063 POINT (-8895686 4892415)\n2 Philadelphia 39.92619 610-480-8919    19145 POINT (-8367892 4855223)\n3 Philadelphia 40.02869 215-483-9900    19128 POINT (-8372298 4870112)\n4   WASHINGTON 40.15655   7248840710    15301 POINT (-8936626 4888717)\n5   Meyersdale 39.80913 814-634-5911    15552 POINT (-8797037 4838244)\n6    Pottstown 40.24273   6103277000    19464 POINT (-8417104 4901278)\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(census_tracts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 6 features and 13 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -8730207 ymin: 4835980 xmax: -8453342 ymax: 4945207\nProjected CRS: WGS 84 / Pseudo-Mercator\n  STATEFP COUNTYFP TRACTCE              GEOIDFQ       GEOID   NAME\n1      42      001  031101 1400000US42001031101 42001031101 311.01\n2      42      013  100400 1400000US42013100400 42013100400   1004\n3      42      013  100500 1400000US42013100500 42013100500   1005\n4      42      013  100800 1400000US42013100800 42013100800   1008\n5      42      013  101900 1400000US42013101900 42013101900   1019\n6      42      011  011200 1400000US42011011200 42011011200    112\n             NAMELSAD STUSPS   NAMELSADCO   STATE_NAME LSAD   ALAND AWATER\n1 Census Tract 311.01     PA Adams County Pennsylvania   CT 3043185      0\n2   Census Tract 1004     PA Blair County Pennsylvania   CT  993724      0\n3   Census Tract 1005     PA Blair County Pennsylvania   CT 1130204      0\n4   Census Tract 1008     PA Blair County Pennsylvania   CT  996553      0\n5   Census Tract 1019     PA Blair County Pennsylvania   CT  573726      0\n6    Census Tract 112     PA Berks County Pennsylvania   CT 1539365   9308\n                        geometry\n1 MULTIPOLYGON (((-8575060 48...\n2 MULTIPOLYGON (((-8730207 49...\n3 MULTIPOLYGON (((-8729297 49...\n4 MULTIPOLYGON (((-8728636 49...\n5 MULTIPOLYGON (((-8728378 49...\n6 MULTIPOLYGON (((-8455198 49...\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnum_hospitals <- nrow(hospitals)\ncat(\"Number of hospitals in dataset:\", num_hospitals, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of hospitals in dataset: 223 \n```\n\n\n:::\n\n```{.r .cell-code}\nnum_tracts <- nrow(census_tracts)\ncat(\"Number of census tracts in dataset:\", num_tracts, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of census tracts in dataset: 3445 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n---- Coordinate Reference Systems ----\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n---- Coordinate Reference Systems ----\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Counties CRS:\\n\"); print(st_crs(pa_counties))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCounties CRS:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 / Pseudo-Mercator \n  wkt:\nPROJCRS[\"WGS 84 / Pseudo-Mercator\",\n    BASEGEOGCRS[\"WGS 84\",\n        ENSEMBLE[\"World Geodetic System 1984 ensemble\",\n            MEMBER[\"World Geodetic System 1984 (Transit)\"],\n            MEMBER[\"World Geodetic System 1984 (G730)\"],\n            MEMBER[\"World Geodetic System 1984 (G873)\"],\n            MEMBER[\"World Geodetic System 1984 (G1150)\"],\n            MEMBER[\"World Geodetic System 1984 (G1674)\"],\n            MEMBER[\"World Geodetic System 1984 (G1762)\"],\n            MEMBER[\"World Geodetic System 1984 (G2139)\"],\n            MEMBER[\"World Geodetic System 1984 (G2296)\"],\n            ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n                LENGTHUNIT[\"metre\",1]],\n            ENSEMBLEACCURACY[2.0]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4326]],\n    CONVERSION[\"Popular Visualisation Pseudo-Mercator\",\n        METHOD[\"Popular Visualisation Pseudo Mercator\",\n            ID[\"EPSG\",1024]],\n        PARAMETER[\"Latitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"False easting\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"easting (X)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"northing (Y)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Web mapping and visualisation.\"],\n        AREA[\"World between 85.06°S and 85.06°N.\"],\n        BBOX[-85.06,-180,85.06,180]],\n    ID[\"EPSG\",3857]]\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nHospitals CRS:\\n\"); print(st_crs(hospitals))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nHospitals CRS:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 / Pseudo-Mercator \n  wkt:\nPROJCRS[\"WGS 84 / Pseudo-Mercator\",\n    BASEGEOGCRS[\"WGS 84\",\n        ENSEMBLE[\"World Geodetic System 1984 ensemble\",\n            MEMBER[\"World Geodetic System 1984 (Transit)\"],\n            MEMBER[\"World Geodetic System 1984 (G730)\"],\n            MEMBER[\"World Geodetic System 1984 (G873)\"],\n            MEMBER[\"World Geodetic System 1984 (G1150)\"],\n            MEMBER[\"World Geodetic System 1984 (G1674)\"],\n            MEMBER[\"World Geodetic System 1984 (G1762)\"],\n            MEMBER[\"World Geodetic System 1984 (G2139)\"],\n            MEMBER[\"World Geodetic System 1984 (G2296)\"],\n            ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n                LENGTHUNIT[\"metre\",1]],\n            ENSEMBLEACCURACY[2.0]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4326]],\n    CONVERSION[\"Popular Visualisation Pseudo-Mercator\",\n        METHOD[\"Popular Visualisation Pseudo Mercator\",\n            ID[\"EPSG\",1024]],\n        PARAMETER[\"Latitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"False easting\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"easting (X)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"northing (Y)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Web mapping and visualisation.\"],\n        AREA[\"World between 85.06°S and 85.06°N.\"],\n        BBOX[-85.06,-180,85.06,180]],\n    ID[\"EPSG\",3857]]\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nCensus Tracts CRS:\\n\"); print(st_crs(census_tracts))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCensus Tracts CRS:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 / Pseudo-Mercator \n  wkt:\nPROJCRS[\"WGS 84 / Pseudo-Mercator\",\n    BASEGEOGCRS[\"WGS 84\",\n        ENSEMBLE[\"World Geodetic System 1984 ensemble\",\n            MEMBER[\"World Geodetic System 1984 (Transit)\"],\n            MEMBER[\"World Geodetic System 1984 (G730)\"],\n            MEMBER[\"World Geodetic System 1984 (G873)\"],\n            MEMBER[\"World Geodetic System 1984 (G1150)\"],\n            MEMBER[\"World Geodetic System 1984 (G1674)\"],\n            MEMBER[\"World Geodetic System 1984 (G1762)\"],\n            MEMBER[\"World Geodetic System 1984 (G2139)\"],\n            MEMBER[\"World Geodetic System 1984 (G2296)\"],\n            ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n                LENGTHUNIT[\"metre\",1]],\n            ENSEMBLEACCURACY[2.0]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4326]],\n    CONVERSION[\"Popular Visualisation Pseudo-Mercator\",\n        METHOD[\"Popular Visualisation Pseudo Mercator\",\n            ID[\"EPSG\",1024]],\n        PARAMETER[\"Latitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"False easting\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"easting (X)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"northing (Y)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Web mapping and visualisation.\"],\n        AREA[\"World between 85.06°S and 85.06°N.\"],\n        BBOX[-85.06,-180,85.06,180]],\n    ID[\"EPSG\",3857]]\n```\n\n\n:::\n:::\n\n\n---\n\n#### Step 2: Get Demographic Data \n\nUse `tidycensus` to download tract-level demographic data for Pennsylvania.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get demographic data from ACS\nlibrary(tidycensus)\nlibrary(dplyr)\nlibrary(sf)\n\nacs_year <- 2022\n\npa_basic <- get_acs(\n  geography = \"tract\",\n  state = \"PA\",\n  variables = c(\n    total_pop = \"B01003_001\",\n    median_income = \"B19013_001\"\n  ),\n  year = acs_year,\n  survey = \"acs5\",\n  geometry = FALSE,\n  output = \"wide\"\n)\n\npa_age <- get_acs(\n  geography = \"tract\",\n  state = \"PA\",\n  variables = c(\n    male_65_66 = \"B01001_020\",\n    male_67_69 = \"B01001_021\",\n    male_70_74 = \"B01001_022\",\n    male_75_79 = \"B01001_023\",\n    male_80_84 = \"B01001_024\",\n    male_85plus = \"B01001_025\",\n    female_65_66 = \"B01001_044\",\n    female_67_69 = \"B01001_045\",\n    female_70_74 = \"B01001_046\",\n    female_75_79 = \"B01001_047\",\n    female_80_84 = \"B01001_048\",\n    female_85plus = \"B01001_049\"\n  ),\n  year = acs_year,\n  survey = \"acs5\",\n  geometry = FALSE\n)\n\npa_age_summary <- pa_age %>%\n  group_by(GEOID) %>%\n  summarize(pop_65_over = sum(estimate, na.rm = TRUE))\n\npa_demo <- pa_basic %>%\n  left_join(pa_age_summary, by = \"GEOID\") %>%\n  select(GEOID, total_popE, median_incomeE, pop_65_over) %>%\n  rename(\n    total_pop = total_popE,\n    median_income = median_incomeE\n  )\n\n# Join to tract boundaries\ncensus_tracts_demo <- census_tracts %>%\n  left_join(pa_demo, by = c(\"GEOID\" = \"GEOID\"))\n\n\n# What year of ACS data?\ncat(\"ACS Year Used:\", acs_year, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nACS Year Used: 2022 \n```\n\n\n:::\n\n```{.r .cell-code}\n# How many tracts have missing income data?\nmissing_income <- sum(is.na(census_tracts_demo$median_income))\ncat(\"Number of tracts with missing income data:\", missing_income, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of tracts with missing income data: 62 \n```\n\n\n:::\n\n```{.r .cell-code}\n# What is the median income across all PA census tracts?\noverall_median_income <- median(census_tracts_demo$median_income, na.rm = TRUE)\ncat(\"Median income across all PA tracts:\", dollar(overall_median_income), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMedian income across all PA tracts: $70,188 \n```\n\n\n:::\n:::\n\n\n\n---\n\n#### Step 3: Define Vulnerable Populations \n\nIdentify census tracts with vulnerable populations based on TWO criteria:\n1. Low median household income (choose an appropriate threshold)\n2. Significant elderly population (choose an appropriate threshold)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#### Step 3: Define Vulnerable Populations ----\n\nincome_threshold <- 50000\nelderly_threshold <- 0.15\n\ncensus_tracts_demo <- census_tracts_demo %>%\n  mutate(\n    pct_elderly =  pop_65_over/ total_pop\n  )\n\nvulnerable_tracts <- census_tracts_demo %>%\n  filter(\n    median_income < income_threshold &\n    pct_elderly > elderly_threshold\n  )\n\nnum_vulnerable <- nrow(vulnerable_tracts)\ntotal_tracts <- nrow(census_tracts_demo)\npct_vulnerable <- (num_vulnerable / total_tracts) * 100\n\ncat(\"Income threshold:\", income_threshold, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIncome threshold: 50000 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Elderly population threshold:\", elderly_threshold * 100, \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nElderly population threshold: 15 %\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Number of vulnerable tracts:\", num_vulnerable, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of vulnerable tracts: 312 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Percentage of PA tracts considered vulnerable:\", round(pct_vulnerable, 2), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPercentage of PA tracts considered vulnerable: 9.06 %\n```\n\n\n:::\n:::\n\n\n---\n\n#### Step 4: Calculate Distance to Hospitals \n\nFor each vulnerable tract, calculate the distance to the nearest hospital.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(units)\n# Transform to appropriate projected CRS\nprojected_crs <- 26918\n\nvulnerable_tracts_proj <- st_transform(vulnerable_tracts, crs = projected_crs)\nhospitals_proj <- st_transform(hospitals, crs = projected_crs)\n\ntract_centroids <- st_centroid(vulnerable_tracts_proj)\n\ndist_matrix <- st_distance(tract_centroids, hospitals_proj)\nnearest_hospital_dist_m <- apply(dist_matrix, 1, min)\n\nnearest_hospital_dist_miles <- as.numeric(nearest_hospital_dist_m) / 1609.34\n\nvulnerable_tracts_proj <- vulnerable_tracts_proj %>%\n  mutate(distance_to_hospital_miles = nearest_hospital_dist_miles)\n\navg_distance <- mean(vulnerable_tracts_proj$distance_to_hospital_miles, na.rm = TRUE)\nmax_distance <- max(vulnerable_tracts_proj$distance_to_hospital_miles, na.rm = TRUE)\nnum_over_15 <- sum(vulnerable_tracts_proj$distance_to_hospital_miles > 15, na.rm = TRUE)\n\ncat(\"Average distance to nearest hospital (miles):\", round(avg_distance, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAverage distance to nearest hospital (miles): 3.17 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Maximum distance to nearest hospital (miles):\", round(max_distance, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMaximum distance to nearest hospital (miles): 18.98 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Number of vulnerable tracts >15 miles from hospital:\", num_over_15, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of vulnerable tracts >15 miles from hospital: 9 \n```\n\n\n:::\n:::\n\n\n---\n\n#### Step 5: Identify Underserved Areas \n\nDefine \"underserved\" as vulnerable tracts that are more than 15 miles from the nearest hospital.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create underserved variable\n\nlibrary(dplyr)\n\nvulnerable_tracts_proj <- vulnerable_tracts_proj %>%\n  mutate(\n    underserved = distance_to_hospital_miles > 15\n  )\n\nnum_underserved <- sum(vulnerable_tracts_proj$underserved, na.rm = TRUE)\ntotal_vulnerable <- nrow(vulnerable_tracts_proj)\npct_underserved <- (num_underserved / total_vulnerable) * 100\n\ncat(\"Number of underserved vulnerable tracts:\", num_underserved, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of underserved vulnerable tracts: 9 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Percentage of vulnerable tracts that are underserved:\", round(pct_underserved, 2), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPercentage of vulnerable tracts that are underserved: 2.88 %\n```\n\n\n:::\n:::\n\n\n---\n\n#### Step 6: Aggregate to County Level\n\nUse spatial joins and aggregation to calculate county-level statistics about vulnerable populations and hospital access.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spatial join tracts to counties\n#### Step 6: Aggregate to County Level ----\n\nvulnerable_tracts_proj <- st_transform(vulnerable_tracts_proj, st_crs(pa_counties))\n\ntracts_with_county <- st_join(vulnerable_tracts_proj, pa_counties, join = st_intersects, left = FALSE)\n\nnames(tracts_with_county)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"STATEFP\"                    \"COUNTYFP\"                  \n [3] \"TRACTCE\"                    \"GEOIDFQ\"                   \n [5] \"GEOID\"                      \"NAME\"                      \n [7] \"NAMELSAD\"                   \"STUSPS\"                    \n [9] \"NAMELSADCO\"                 \"STATE_NAME\"                \n[11] \"LSAD\"                       \"ALAND\"                     \n[13] \"AWATER\"                     \"total_pop\"                 \n[15] \"median_income\"              \"pop_65_over\"               \n[17] \"pct_elderly\"                \"distance_to_hospital_miles\"\n[19] \"underserved\"                \"OBJECTID\"                  \n[21] \"MSLINK\"                     \"COUNTY_NAM\"                \n[23] \"COUNTY_NUM\"                 \"FIPS_COUNT\"                \n[25] \"COUNTY_ARE\"                 \"COUNTY_PER\"                \n[27] \"NUMERIC_LA\"                 \"COUNTY_N_1\"                \n[29] \"AREA_SQ_MI\"                 \"SOUND\"                     \n[31] \"SPREAD_SHE\"                 \"IMAGE_NAME\"                \n[33] \"NOTE_FILE\"                  \"VIDEO\"                     \n[35] \"DISTRICT_N\"                 \"PA_CTY_COD\"                \n[37] \"MAINT_CTY_\"                 \"DISTRICT_O\"                \n[39] \"geometry\"                  \n```\n\n\n:::\n\n```{.r .cell-code}\ncounty_summary <- tracts_with_county %>%\n  st_drop_geometry() %>%\n  group_by(NAMELSADCO) %>%\n  summarize(\n    num_vulnerable_tracts = n(),\n    num_underserved_tracts = sum(underserved, na.rm = TRUE),\n    pct_underserved = (num_underserved_tracts / num_vulnerable_tracts) * 100,\n    avg_distance_miles = mean(distance_to_hospital_miles, na.rm = TRUE),\n    total_vulnerable_pop = sum(total_pop, na.rm = TRUE)\n  ) %>%\n  arrange(desc(pct_underserved))\n\nhead(county_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  NAMELSADCO        num_vulnerable_tracts num_underserved_tracts pct_underserved\n  <chr>                             <int>                  <int>           <dbl>\n1 Cameron County                        1                      1           100  \n2 Centre County                         2                      2           100  \n3 Forest County                         8                      8           100  \n4 Monroe County                         1                      1           100  \n5 Juniata County                        7                      5            71.4\n6 Clearfield County                     6                      4            66.7\n# ℹ 2 more variables: avg_distance_miles <dbl>, total_vulnerable_pop <dbl>\n```\n\n\n:::\n\n```{.r .cell-code}\n# Aggregate statistics by county\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop5_underserved <- county_summary %>%\n  arrange(desc(pct_underserved)) %>%\n  slice(1:5)\nprint(top5_underserved)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 6\n  NAMELSADCO     num_vulnerable_tracts num_underserved_tracts pct_underserved\n  <chr>                          <int>                  <int>           <dbl>\n1 Cameron County                     1                      1           100  \n2 Centre County                      2                      2           100  \n3 Forest County                      8                      8           100  \n4 Monroe County                      1                      1           100  \n5 Juniata County                     7                      5            71.4\n# ℹ 2 more variables: avg_distance_miles <dbl>, total_vulnerable_pop <dbl>\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop_vuln_far <- county_summary %>%\n  arrange(desc(total_vulnerable_pop)) %>%\n  slice(1:5)\nprint(top_vuln_far)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 6\n  NAMELSADCO        num_vulnerable_tracts num_underserved_tracts pct_underserved\n  <chr>                             <int>                  <int>           <dbl>\n1 Philadelphia Cou…                    57                      0               0\n2 Allegheny County                     59                      0               0\n3 Luzerne County                       18                      0               0\n4 Westmoreland Cou…                    23                      0               0\n5 Fayette County                       12                      0               0\n# ℹ 2 more variables: avg_distance_miles <dbl>, total_vulnerable_pop <dbl>\n```\n\n\n:::\n:::\n\nMost underserved counties tend to be located in rural northern and western Pennsylvania, where hospital density is lower and population centers are more dispersed. Urban counties (like Philadelphia or Allegheny) show fewer underserved tracts due to higher hospital accessibility.\n\n---\n\n#### Step 7: Create Summary Table \n\nCreate a professional table showing the top 10 priority counties for healthcare investment.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create and format priority counties table\n#### Step 7: Create Summary Table ----\n\nlibrary(knitr)\nlibrary(scales)\n\npriority_metric <- \"pct_underserved\"\n\npriority_counties <- county_summary %>%\n  arrange(desc(!!sym(priority_metric))) %>%\n  slice(1:10) %>%\n  mutate(\n    num_vulnerable_tracts = comma(num_vulnerable_tracts),\n    num_underserved_tracts = comma(num_underserved_tracts),\n    pct_underserved = percent(pct_underserved / 100, accuracy = 0.1),\n    avg_distance_miles = round(avg_distance_miles, 1),\n    total_vulnerable_pop = comma(total_vulnerable_pop)\n  ) %>%\n  rename(\n    `County` = NAMELSADCO,\n    `Vulnerable Tracts` = num_vulnerable_tracts,\n    `Underserved Tracts` = num_underserved_tracts,\n    `% Underserved` = pct_underserved,\n    `Avg Distance (mi)` = avg_distance_miles,\n    `Total Vulnerable Population` = total_vulnerable_pop\n  )\n\nkable(\n  priority_counties,\n  caption = \"Table 1. Top 10 Pennsylvania Counties Prioritized for Healthcare Investment\",\n  align = \"lccccc\",\n  format = \"markdown\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Table 1. Top 10 Pennsylvania Counties Prioritized for Healthcare Investment\n\n|County            | Vulnerable Tracts | Underserved Tracts | % Underserved | Avg Distance (mi) | Total Vulnerable Population |\n|:-----------------|:-----------------:|:------------------:|:-------------:|:-----------------:|:---------------------------:|\n|Cameron County    |         1         |         1          |    100.0%     |       18.7        |            1,988            |\n|Centre County     |         2         |         2          |    100.0%     |       15.2        |            6,654            |\n|Forest County     |         8         |         8          |    100.0%     |       18.4        |           27,836            |\n|Monroe County     |         1         |         1          |    100.0%     |       17.7        |            1,299            |\n|Juniata County    |         7         |         5          |     71.4%     |       14.0        |           16,390            |\n|Clearfield County |         6         |         4          |     66.7%     |       15.9        |           17,238            |\n|Adams County      |         1         |         0          |     0.0%      |        0.2        |            3,908            |\n|Allegheny County  |        59         |         0          |     0.0%      |        2.1        |           146,496           |\n|Armstrong County  |         3         |         0          |     0.0%      |        4.3        |            7,376            |\n|Beaver County     |         9         |         0          |     0.0%      |        2.3        |           20,794            |\n\n\n:::\n:::\n\n\n---\n\n## Part 2: Comprehensive Visualization \n\nUsing the skills from Week 3 (Data Visualization), create publication-quality maps and charts.\n\n### Map 1: County-Level Choropleth \n\nCreate a choropleth map showing healthcare access challenges at the county level.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(stringr)\n\ncounty_summary <- county_summary %>%\n  mutate(NAMELSADCO = str_replace(NAMELSADCO, \" County$\", \"\"))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nView(pa_counties)\nView(county_summary)\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create county-level access map\n#### Part 2: County-Level Choropleth ----\n\nlibrary(ggplot2)\nlibrary(sf)\nlibrary(scales)\n\npa_counties_proj <- st_transform(pa_counties, 26918)\nhospitals_proj <- st_transform(hospitals, 26918)\n\n\ncounty_summary_map <- pa_counties_proj %>%\n  mutate(COUNTY_NAM = tolower(COUNTY_NAM)) %>%\n  left_join(\n    county_summary %>%\n      mutate(NAMELSADCO = tolower(NAMELSADCO)),\n    by = c(\"COUNTY_NAM\" = \"NAMELSADCO\")\n  )\n\n\nggplot() +\n  geom_sf(\n    data = county_summary_map,\n    aes(fill = pct_underserved),\n    color = \"white\",\n    size = 0.2\n  ) +\n\n  scale_fill_gradient(\n    low = \"#DEEBF7\",\n    high = \"#2171B5\",\n    name = \"% Underserved Tracts\",\n    labels = function(x) paste0(round(x, 0), \"%\"),\n    na.value = \"grey90\"\n  ) +\n\n  labs(\n    title = \"Healthcare Access Challenges Across Pennsylvania Counties\",\n    subtitle = \"Percentage of vulnerable tracts that are more than 15 miles from the nearest hospital\",\n    caption = \"Data sources: ACS 2022 (via tidycensus), Pennsylvania hospital data (Week 4 lecture)\"\n  ) +\n\n  theme_void(base_size = 12) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 14, hjust = 0.5),\n    plot.subtitle = element_text(size = 11, hjust = 0.5),\n    plot.caption = element_text(size = 9, hjust = 0.95, color = \"gray40\"),\n    legend.position = \"right\",\n    legend.title = element_text(size = 10, face = \"bold\"),\n    legend.text = element_text(size = 9)\n  )\n```\n\n::: {.cell-output-display}\n![](Qianmu_Zheng_assignment2_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n---\n\n### Map 2: Detailed Vulnerability Map \n\nCreate a map highlighting underserved vulnerable tracts.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create detailed tract-level map\n#### Part 2: Map 2 - Detailed Vulnerability Map ----\n\npa_counties_proj <- st_transform(pa_counties, 26918)\nhospitals_proj <- st_transform(hospitals, 26918)\nvulnerable_tracts_proj <- st_transform(vulnerable_tracts_proj, 26918)\n\ntract_map_data <- vulnerable_tracts_proj %>%\n  mutate(\n    tract_status = case_when(\n      underserved ~ \"Underserved Vulnerable Tract\",\n      TRUE ~ \"Other Vulnerable Tract\"\n    )\n  )\n\nggplot() +\n  geom_sf(data = pa_counties_proj, fill = \"gray95\", color = \"white\", size = 0.3) +\n  \n  geom_sf(\n    data = tract_map_data,\n    aes(fill = tract_status),\n    color = NA,\n    alpha = 0.9\n  ) +\n  \n  geom_sf(\n    data = hospitals_proj,\n    color = \"red\",\n    size = 1.2,\n    alpha = 0.8\n  ) +\n  \n  scale_fill_manual(\n    values = c(\n      \"Underserved Vulnerable Tract\" = \"#d73027\",\n      \"Other Vulnerable Tract\" = \"#fee090\"\n    ),\n    name = \"Tract Type\"\n  ) +\n  \n  labs(\n    title = \"Underserved Vulnerable Tracts in Pennsylvania\",\n    subtitle = \"Vulnerable tracts (low income & elderly) more than 15 miles from the nearest hospital are shown in red\",\n    caption = \"Data: ACS 2022 (via tidycensus) and PA hospital data (Week 4 lecture)\"\n  ) +\n  \n  theme_void(base_size = 11) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 14, hjust = 0.5),\n    plot.subtitle = element_text(size = 11, hjust = 0.5, color = \"gray20\"),\n    plot.caption = element_text(size = 9, color = \"gray40\", hjust = 0.95),\n    legend.position = \"bottom\",\n    legend.title = element_text(face = \"bold\", size = 10),\n    legend.text = element_text(size = 9)\n  )\n```\n\n::: {.cell-output-display}\n![](Qianmu_Zheng_assignment2_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n---\n\n### Chart: Distribution Analysis\n\nCreate a visualization showing the distribution of distances to hospitals for vulnerable populations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create distribution visualization\n#### Chart: Distribution Analysis ----\n\nlibrary(ggplot2)\nlibrary(scales)\n\nggplot(vulnerable_tracts_proj, aes(x = distance_to_hospital_miles)) +\n  geom_histogram(\n    aes(y = after_stat(density)),\n    bins = 30,\n    fill = \"#74c476\",\n    color = \"white\",\n    alpha = 0.8\n  ) +\n  geom_density(color = \"#006d2c\", linewidth = 1) +\n  geom_vline(xintercept = 15, linetype = \"dashed\", color = \"red\", linewidth = 1) +\n  labs(\n    title = \"Distribution of Distances to Nearest Hospital for Vulnerable Tracts\",\n    subtitle = \"Dashed red line indicates the 15-mile underserved threshold\",\n    x = \"Distance to Nearest Hospital (miles)\",\n    y = \"Density\",\n    caption = \"Data: ACS 2022 (via tidycensus) and PA hospital data (Week 4 lecture)\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(\n    plot.title = element_text(face = \"bold\", hjust = 0.5, size = 14),\n    plot.subtitle = element_text(size = 11, hjust = 0.5, color = \"gray30\"),\n    plot.caption = element_text(size = 9, color = \"gray40\", hjust = 0.95),\n    axis.title = element_text(face = \"bold\")\n  )\n```\n\n::: {.cell-output-display}\n![](Qianmu_Zheng_assignment2_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n---\n\n## Part 3: Bring Your Own Data Analysis \n\nChoose your own additional spatial dataset and conduct a supplementary analysis.\n\n1. **Find and load additional data**\n   - Document your data source\n   - Check and standardize the CRS\n   - Provide basic summary statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load your additional dataset\nbase_path = \"D:\\\\Desktop\\\\musa\\\\5080_policy\\\\portfolio-setup-xqdqc-hub\\\\assignments\\\\assignment_2\\\\data\"\n\nschools <- st_read(file.path(base_path, \"Schools\\\\Schools.shp\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Schools' from data source \n  `D:\\Desktop\\musa\\5080_policy\\portfolio-setup-xqdqc-hub\\assignments\\assignment_2\\data\\Schools\\Schools.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 495 features and 14 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -8378628 ymin: 4852555 xmax: -8345686 ymax: 4884813\nProjected CRS: WGS 84 / Pseudo-Mercator\n```\n\n\n:::\n\n```{.r .cell-code}\ncrime <- st_read(file.path(base_path,\"incidents_part1_part2\\\\incidents_part1_part2.shp\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `incidents_part1_part2' from data source \n  `D:\\Desktop\\musa\\5080_policy\\portfolio-setup-xqdqc-hub\\assignments\\assignment_2\\data\\incidents_part1_part2\\incidents_part1_part2.shp' \n  using driver `ESRI Shapefile'\nreplacing null geometries with empty geometries\nSimple feature collection with 160388 features and 13 fields (with 6744 geometries empty)\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -80.50237 ymin: 39.87688 xmax: -74.95784 ymax: 42.22434\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nbike_net <- st_read(file.path(base_path,\"Bike_Network\\\\Bike_Network.shp\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Bike_Network' from data source \n  `D:\\Desktop\\musa\\5080_policy\\portfolio-setup-xqdqc-hub\\assignments\\assignment_2\\data\\Bike_Network\\Bike_Network.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 5225 features and 8 fields\nGeometry type: LINESTRING\nDimension:     XY\nBounding box:  xmin: -8378937 ymin: 4847835 xmax: -8345146 ymax: 4883978\nProjected CRS: WGS 84 / Pseudo-Mercator\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"Schools CRS:\\n\"); print(st_crs(schools))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSchools CRS:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 / Pseudo-Mercator \n  wkt:\nPROJCRS[\"WGS 84 / Pseudo-Mercator\",\n    BASEGEOGCRS[\"WGS 84\",\n        ENSEMBLE[\"World Geodetic System 1984 ensemble\",\n            MEMBER[\"World Geodetic System 1984 (Transit)\"],\n            MEMBER[\"World Geodetic System 1984 (G730)\"],\n            MEMBER[\"World Geodetic System 1984 (G873)\"],\n            MEMBER[\"World Geodetic System 1984 (G1150)\"],\n            MEMBER[\"World Geodetic System 1984 (G1674)\"],\n            MEMBER[\"World Geodetic System 1984 (G1762)\"],\n            MEMBER[\"World Geodetic System 1984 (G2139)\"],\n            MEMBER[\"World Geodetic System 1984 (G2296)\"],\n            ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n                LENGTHUNIT[\"metre\",1]],\n            ENSEMBLEACCURACY[2.0]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4326]],\n    CONVERSION[\"Popular Visualisation Pseudo-Mercator\",\n        METHOD[\"Popular Visualisation Pseudo Mercator\",\n            ID[\"EPSG\",1024]],\n        PARAMETER[\"Latitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"False easting\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"easting (X)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"northing (Y)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Web mapping and visualisation.\"],\n        AREA[\"World between 85.06°S and 85.06°N.\"],\n        BBOX[-85.06,-180,85.06,180]],\n    ID[\"EPSG\",3857]]\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nCrime Incidents CRS:\\n\"); print(st_crs(crime))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCrime Incidents CRS:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 \n  wkt:\nGEOGCRS[\"WGS 84\",\n    DATUM[\"World Geodetic System 1984\",\n        ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"latitude\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"longitude\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4326]]\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nBike Network CRS:\\n\"); print(st_crs(bike_net))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nBike Network CRS:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 / Pseudo-Mercator \n  wkt:\nPROJCRS[\"WGS 84 / Pseudo-Mercator\",\n    BASEGEOGCRS[\"WGS 84\",\n        ENSEMBLE[\"World Geodetic System 1984 ensemble\",\n            MEMBER[\"World Geodetic System 1984 (Transit)\"],\n            MEMBER[\"World Geodetic System 1984 (G730)\"],\n            MEMBER[\"World Geodetic System 1984 (G873)\"],\n            MEMBER[\"World Geodetic System 1984 (G1150)\"],\n            MEMBER[\"World Geodetic System 1984 (G1674)\"],\n            MEMBER[\"World Geodetic System 1984 (G1762)\"],\n            MEMBER[\"World Geodetic System 1984 (G2139)\"],\n            MEMBER[\"World Geodetic System 1984 (G2296)\"],\n            ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n                LENGTHUNIT[\"metre\",1]],\n            ENSEMBLEACCURACY[2.0]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4326]],\n    CONVERSION[\"Popular Visualisation Pseudo-Mercator\",\n        METHOD[\"Popular Visualisation Pseudo Mercator\",\n            ID[\"EPSG\",1024]],\n        PARAMETER[\"Latitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"False easting\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"easting (X)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"northing (Y)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Web mapping and visualisation.\"],\n        AREA[\"World between 85.06°S and 85.06°N.\"],\n        BBOX[-85.06,-180,85.06,180]],\n    ID[\"EPSG\",3857]]\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrime <- st_transform(crime, 3857)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"\\nSchools:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nSchools:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Number of schools:\", nrow(schools), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of schools: 495 \n```\n\n\n:::\n\n```{.r .cell-code}\nprint(st_geometry_type(schools) %>% table())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n.\n          GEOMETRY              POINT         LINESTRING            POLYGON \n                 0                495                  0                  0 \n        MULTIPOINT    MULTILINESTRING       MULTIPOLYGON GEOMETRYCOLLECTION \n                 0                  0                  0                  0 \n    CIRCULARSTRING      COMPOUNDCURVE       CURVEPOLYGON         MULTICURVE \n                 0                  0                  0                  0 \n      MULTISURFACE              CURVE            SURFACE  POLYHEDRALSURFACE \n                 0                  0                  0                  0 \n               TIN           TRIANGLE \n                 0                  0 \n```\n\n\n:::\n\n```{.r .cell-code}\nprint(summary(st_bbox(schools)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n-8378628 -8353921 -1746565 -1746736  4860620  4884814 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nCrime Incidents:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCrime Incidents:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Number of records:\", nrow(crime), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of records: 160388 \n```\n\n\n:::\n\n```{.r .cell-code}\nprint(st_geometry_type(crime) %>% table())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n.\n          GEOMETRY              POINT         LINESTRING            POLYGON \n                 0             160388                  0                  0 \n        MULTIPOINT    MULTILINESTRING       MULTIPOLYGON GEOMETRYCOLLECTION \n                 0                  0                  0                  0 \n    CIRCULARSTRING      COMPOUNDCURVE       CURVEPOLYGON         MULTICURVE \n                 0                  0                  0                  0 \n      MULTISURFACE              CURVE            SURFACE  POLYHEDRALSURFACE \n                 0                  0                  0                  0 \n               TIN           TRIANGLE \n                 0                  0 \n```\n\n\n:::\n\n```{.r .cell-code}\nprint(summary(st_bbox(crime)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n-8961483 -8498572 -1748101 -1815760  4934711  5194643 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nBike Network:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nBike Network:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Number of segments:\", nrow(bike_net), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of segments: 5225 \n```\n\n\n:::\n\n```{.r .cell-code}\nprint(st_geometry_type(bike_net) %>% table())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n.\n          GEOMETRY              POINT         LINESTRING            POLYGON \n                 0                  0               5225                  0 \n        MULTIPOINT    MULTILINESTRING       MULTIPOLYGON GEOMETRYCOLLECTION \n                 0                  0                  0                  0 \n    CIRCULARSTRING      COMPOUNDCURVE       CURVEPOLYGON         MULTICURVE \n                 0                  0                  0                  0 \n      MULTISURFACE              CURVE            SURFACE  POLYHEDRALSURFACE \n                 0                  0                  0                  0 \n               TIN           TRIANGLE \n                 0                  0 \n```\n\n\n:::\n\n```{.r .cell-code}\nprint(summary(st_bbox(bike_net)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n-8378937 -8353594 -1748656 -1748068  4856871  4883978 \n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- What dataset did you choose and why?\n\nI have chosen School dataset because I'm interested in young children issue.\n\n- What is the data source and date?\n\nCrime Incidents is in 2024, and I also have school dataset and bike network dataset.\n\n- How many features does it contain?\n\nNumber of schools is 495, number of crime records is 160388, number of bike network segments is 5225.\n\n- What CRS is it in? Did you need to transform it?\n\nThe CRS of schools and bike network data is EPSG 3857, the CRS of crime data is EPSG 4326. So I have got crime data transformed.\n\n---\n\n2. **Pose a research question**\n\nWrite a clear research statement that your analysis will answer.\n\nThis analysis investigates whether school zones in Philadelphia are safe environments, by examining the number of nearby crime incidents.\n\n---\n\n3. **Conduct spatial analysis**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Your spatial analysis\nschool_buffers <- st_buffer(schools, dist = 1000)\n\ncrime_join <- st_join(crime, school_buffers, join = st_within, left = FALSE)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nView(crime_join)\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nschool_crime_count <- crime_join %>%\n  st_drop_geometry() %>%\n  group_by(school_nam) %>%\n  summarize(crime_count = n())\n\nschools_with_crime <- schools %>%\n  left_join(school_crime_count, by = \"school_nam\") %>%\n  mutate(crime_count = replace_na(crime_count, 0))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(schools_with_crime)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 6 features and 15 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -8366653 ymin: 4857549 xmax: -8346614 ymax: 4878677\nProjected CRS: WGS 84 / Pseudo-Mercator\n        aun school_num location_i                     school_nam\n1 226518902         NA       <NA> ST MARYS INTERPAROCHIAL SCHOOL\n2 226518722         NA       <NA>               ST MARTHA SCHOOL\n3 226514052         NA       <NA>           MATERNITY BVM SCHOOL\n4 226514852         NA       <NA>     OUR LADY OF CALVARY SCHOOL\n5 226511102         NA       <NA>         CHRIST THE KING SCHOOL\n6 300511820         NA       <NA>     BEGINNINGS LEARNING CENTER\n                      school_n_1             street_add zip_code     phone_numb\n1 ST MARYS INTERPAROCHIAL SCHOOL          440 LOCUST ST    19106 (215) 923-7522\n2               ST MARTHA SCHOOL       11321 ACADEMY RD    19154 (215) 632-0320\n3           MATERNITY BVM SCHOOL 9322 OLD BUSTLETON AVE    19115 (215) 673-0235\n4     OUR LADY OF CALVARY SCHOOL       11023 KIPLING LN    19154 (215) 637-1648\n5         CHRIST THE KING SCHOOL   3205 CHESTERFIELD RD    19114 (215) 632-1375\n6     BEGINNINGS LEARNING CENTER          620 S 10TH ST    19147 (215) 627-3668\n          grade_leve grade_org enrollment type  type_speci objectid crime_count\n1  ELEMENTARY/MIDDLE       K-8         NA    3 ARCHDIOCESE        1        2041\n2  ELEMENTARY/MIDDLE    PREK-8         NA    3 ARCHDIOCESE        2         230\n3  ELEMENTARY/MIDDLE    PREK-8         NA    3 ARCHDIOCESE        3         310\n4  ELEMENTARY/MIDDLE    PREK-8         NA    3 ARCHDIOCESE        4         307\n5  ELEMENTARY/MIDDLE    PREK-8         NA    3 ARCHDIOCESE        5         236\n6 PRE-K/KINDERGARTEN    PREK-K         NA    3     PRIVATE        6        1937\n                  geometry\n1 POINT (-8365617 4858106)\n2 POINT (-8347297 4878677)\n3 POINT (-8353302 4877854)\n4 POINT (-8346614 4877484)\n5 POINT (-8348439 4876888)\n6 POINT (-8366653 4857549)\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbike_in_buffers <- st_intersection(bike_net, school_buffers)\n\nbike_coverage <- bike_in_buffers %>%\n  st_drop_geometry() %>%\n  group_by(school_nam) %>%\n  summarize(bike_miles = sum(st_length(bike_in_buffers) / 5280))\n\nschools_with_bike <- schools_with_crime %>%\n  left_join(bike_coverage, by = c(\"school_nam\")) %>%\n  mutate(bike_miles = replace_na(bike_miles))\n\nhead(schools_with_bike)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 6 features and 16 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -8366653 ymin: 4857549 xmax: -8346614 ymax: 4878677\nProjected CRS: WGS 84 / Pseudo-Mercator\n        aun school_num location_i                     school_nam\n1 226518902         NA       <NA> ST MARYS INTERPAROCHIAL SCHOOL\n2 226518722         NA       <NA>               ST MARTHA SCHOOL\n3 226514052         NA       <NA>           MATERNITY BVM SCHOOL\n4 226514852         NA       <NA>     OUR LADY OF CALVARY SCHOOL\n5 226511102         NA       <NA>         CHRIST THE KING SCHOOL\n6 300511820         NA       <NA>     BEGINNINGS LEARNING CENTER\n                      school_n_1             street_add zip_code     phone_numb\n1 ST MARYS INTERPAROCHIAL SCHOOL          440 LOCUST ST    19106 (215) 923-7522\n2               ST MARTHA SCHOOL       11321 ACADEMY RD    19154 (215) 632-0320\n3           MATERNITY BVM SCHOOL 9322 OLD BUSTLETON AVE    19115 (215) 673-0235\n4     OUR LADY OF CALVARY SCHOOL       11023 KIPLING LN    19154 (215) 637-1648\n5         CHRIST THE KING SCHOOL   3205 CHESTERFIELD RD    19114 (215) 632-1375\n6     BEGINNINGS LEARNING CENTER          620 S 10TH ST    19147 (215) 627-3668\n          grade_leve grade_org enrollment type  type_speci objectid crime_count\n1  ELEMENTARY/MIDDLE       K-8         NA    3 ARCHDIOCESE        1        2041\n2  ELEMENTARY/MIDDLE    PREK-8         NA    3 ARCHDIOCESE        2         230\n3  ELEMENTARY/MIDDLE    PREK-8         NA    3 ARCHDIOCESE        3         310\n4  ELEMENTARY/MIDDLE    PREK-8         NA    3 ARCHDIOCESE        4         307\n5  ELEMENTARY/MIDDLE    PREK-8         NA    3 ARCHDIOCESE        5         236\n6 PRE-K/KINDERGARTEN    PREK-K         NA    3     PRIVATE        6        1937\n    bike_miles                 geometry\n1 484.4795 [m] POINT (-8365617 4858106)\n2 484.4795 [m] POINT (-8347297 4878677)\n3 484.4795 [m] POINT (-8353302 4877854)\n4 484.4795 [m] POINT (-8346614 4877484)\n5 484.4795 [m] POINT (-8348439 4876888)\n6 484.4795 [m] POINT (-8366653 4857549)\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary_tbl <- schools_with_bike %>%\n  st_drop_geometry() %>%\n  summarize(\n    total_schools = n(),\n    avg_crime = mean(crime_count, na.rm = TRUE),\n    avg_bike = mean(bike_miles, na.rm = TRUE)\n  )\n\nprint(summary_tbl)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  total_schools avg_crime     avg_bike\n1           495  1460.842 484.4795 [m]\n```\n\n\n:::\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = schools_with_crime) +\n  geom_sf(aes(color = crime_count), size = 2) +\n  scale_color_viridis_c(\n    option = \"plasma\",\n    trans = \"sqrt\",\n    name = \"Crime Count\"\n  ) +\n  labs(\n    title = \"Crime Incidents Within 1000ft of Philadelphia Schools\",\n    subtitle = \"Each point represents a school, colored by number of nearby crime incidents\",\n    caption = \"Data: OpenDataPhilly | Analysis: MUSA 5080 Assignment 3\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 14, hjust = 0.5),\n    plot.subtitle = element_text(size = 10, hjust = 0.5, color = \"gray30\"),\n    legend.position = \"right\"\n  )\n```\n\n::: {.cell-output-display}\n![](Qianmu_Zheng_assignment2_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(schools_with_crime, aes(x = crime_count)) +\n  geom_histogram(\n    bins = 30,\n    fill = \"pink\",\n    color = \"white\",\n    alpha = 0.8\n  ) +\n  labs(\n    title = \"Distribution of Crime Incidents Within 1000ft of Schools\",\n    subtitle = \"Each bar represents the number of schools by nearby crime count\",\n    x = \"Number of Crime Incidents (within 1000ft)\",\n    y = \"Number of Schools\",\n    caption = \"Data: OpenDataPhilly | Analysis: MUSA 5080 Assignment 3\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 14, hjust = 0.5),\n    plot.subtitle = element_text(size = 10, hjust = 0.5, color = \"gray30\"),\n    plot.caption = element_text(size = 8, color = \"gray50\", hjust = 0.95)\n  )\n```\n\n::: {.cell-output-display}\n![](Qianmu_Zheng_assignment2_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\n**My interpretation:**\nThe majority of Philadelphia schools experience a moderate number of nearby crime incidents, with most falling below 2,000 cases within a 1,000-ft radius. However, a few schools stand out as clear hotspots, with significantly higher counts exceeding 6,000 incidents, concentrated primarily in central and southern parts of the city. The histogram confirms this right-skewed distribution, where a small proportion of schools account for a disproportionately large share of nearby crimes. These findings suggest that while most school zones remain relatively safe, targeted safety interventions and “Safe Routes to School” programs should prioritize the high-crime areas identified in the analysis.\n",
    "supporting": [
      "Qianmu_Zheng_assignment2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}